-- White Mountains Redline: initial spatial schema
-- Run in a Supabase project after enabling PostGIS.

create extension if not exists postgis with schema extensions;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text unique,
  display_name text,
  is_public boolean not null default true,
  created_at timestamptz not null default now()
);

create table if not exists public.trails (
  id bigint generated by default as identity primary key,
  slug text not null unique,
  name text not null,
  region text not null,
  source_label text,
  source_ref text,
  data_status text not null default 'unverified' check (data_status in ('unverified','verified','retired')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.trail_segments (
  id bigint generated by default as identity primary key,
  trail_id bigint not null references public.trails(id) on delete cascade,
  segment_key text not null unique,
  segment_name text not null,
  miles numeric(8,3) not null check (miles >= 0),
  geom extensions.geometry(LineString, 4326) not null,
  source_label text,
  source_ref text,
  verification_notes text,
  data_status text not null default 'unverified' check (data_status in ('unverified','verified','retired')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists trail_segments_geom_gix on public.trail_segments using gist (geom);
create index if not exists trail_segments_trail_id_idx on public.trail_segments(trail_id);

create table if not exists public.activities (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  title text,
  activity_date date,
  source text not null default 'manual' check (source in ('manual','gpx','garmin','strava','other')),
  geom extensions.geometry(MultiLineString, 4326),
  distance_miles numeric(8,3),
  trip_report_url text,
  notes text,
  created_at timestamptz not null default now()
);

create index if not exists activities_geom_gix on public.activities using gist (geom);
create index if not exists activities_user_id_idx on public.activities(user_id);

create table if not exists public.segment_completions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  segment_id bigint not null references public.trail_segments(id) on delete cascade,
  activity_id bigint references public.activities(id) on delete set null,
  completed_on date,
  completion_method text not null default 'manual' check (completion_method in ('manual','gpx_match','admin')),
  match_confidence numeric(5,4),
  notes text,
  created_at timestamptz not null default now(),
  unique(user_id, segment_id)
);

create index if not exists segment_completions_user_id_idx on public.segment_completions(user_id);

alter table public.profiles enable row level security;
alter table public.activities enable row level security;
alter table public.segment_completions enable row level security;
alter table public.trails enable row level security;
alter table public.trail_segments enable row level security;

create policy "public profiles are viewable" on public.profiles
  for select using (is_public = true or auth.uid() = id);
create policy "users create own profile" on public.profiles
  for insert with check (auth.uid() = id);
create policy "users update own profile" on public.profiles
  for update using (auth.uid() = id);

create policy "users read own activities" on public.activities
  for select using (auth.uid() = user_id);
create policy "users create own activities" on public.activities
  for insert with check (auth.uid() = user_id);
create policy "users update own activities" on public.activities
  for update using (auth.uid() = user_id);
create policy "users delete own activities" on public.activities
  for delete using (auth.uid() = user_id);

create policy "users read own completions" on public.segment_completions
  for select using (auth.uid() = user_id);
create policy "users create own completions" on public.segment_completions
  for insert with check (auth.uid() = user_id);
create policy "users update own completions" on public.segment_completions
  for update using (auth.uid() = user_id);
create policy "users delete own completions" on public.segment_completions
  for delete using (auth.uid() = user_id);

-- Public trail geometry is read-only for normal app users.
create policy "trails are public read" on public.trails for select using (true);
create policy "segments are public read" on public.trail_segments for select using (true);
