-- White Mountains Redline: raw source GIS staging layer.
-- Raw authoritative-source features are not challenge segments and are never verified by import alone.

create extension if not exists postgis with schema extensions;

create table if not exists public.import_batches (
  id bigint generated by default as identity primary key,
  source_provider text not null,
  source_dataset text not null,
  source_url text not null,
  requested_envelope extensions.geometry(Polygon, 4326),
  requested_fields text[] not null default '{}',
  imported_at timestamptz not null default now(),
  feature_count integer not null default 0 check (feature_count >= 0),
  named_feature_count integer not null default 0 check (named_feature_count >= 0),
  unnamed_feature_count integer not null default 0 check (unnamed_feature_count >= 0),
  unique_trail_name_count integer not null default 0 check (unique_trail_name_count >= 0),
  malformed_feature_count integer not null default 0 check (malformed_feature_count >= 0),
  summary jsonb not null default '{}'::jsonb,
  notes text
);

create table if not exists public.source_trail_features (
  id bigint generated by default as identity primary key,
  import_batch_id bigint references public.import_batches(id) on delete set null,
  source_provider text not null,
  source_dataset text not null,
  source_feature_id text not null,
  source_url text not null,
  imported_at timestamptz not null default now(),
  original_properties jsonb not null default '{}'::jsonb,
  geom extensions.geometry(Geometry, 4326) not null,
  region_hint text,
  reconciliation_status text not null default 'raw'
    check (reconciliation_status in ('raw','normalized','needs_review','matched_candidate','rejected','promoted')),
  trail_name text,
  segment_length numeric,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(source_provider, source_dataset, source_feature_id)
);

create index if not exists source_trail_features_geom_gix on public.source_trail_features using gist (geom);
create index if not exists source_trail_features_source_idx on public.source_trail_features(source_provider, source_dataset);
create index if not exists source_trail_features_reconciliation_idx on public.source_trail_features(reconciliation_status);
create index if not exists source_trail_features_trail_name_idx on public.source_trail_features(trail_name);

alter table public.import_batches enable row level security;
alter table public.source_trail_features enable row level security;

create policy "source import batches are public read" on public.import_batches for select using (true);
create policy "source trail features are public read" on public.source_trail_features for select using (true);
