-- White Mountains Redline: future persisted trail-level reconciliation workspace.
-- Accepted trail-level reconciliation is not a verified TrailSegment.

create table if not exists public.challenge_editions (
  id bigint generated by default as identity primary key,
  edition_key text not null unique,
  label text not null,
  notes text,
  created_at timestamptz not null default now()
);

create table if not exists public.challenge_inventory_items (
  id bigint generated by default as identity primary key,
  edition_id bigint not null references public.challenge_editions(id) on delete cascade,
  item_key text not null,
  display_name text not null,
  normalized_name text not null,
  region_hint text,
  source_notes text,
  review_status text not null default 'unreviewed'
    check (review_status in ('unreviewed','candidate_found','needs_review','accepted','rejected','unmatched')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(edition_id, item_key)
);

create table if not exists public.reconciliation_candidates (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint not null references public.challenge_inventory_items(id) on delete cascade,
  source_provider text not null,
  source_trail_normalized_name text not null,
  source_trail_display_name text not null,
  source_feature_ids text[] not null default '{}',
  score numeric(5,2) not null check (score >= 0 and score <= 100),
  evidence jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  unique(inventory_item_id, source_provider, source_trail_normalized_name)
);

create table if not exists public.reconciliation_decisions (
  id bigint generated by default as identity primary key,
  inventory_item_id bigint not null references public.challenge_inventory_items(id) on delete cascade,
  candidate_id bigint references public.reconciliation_candidates(id) on delete set null,
  decision text not null check (decision in ('accepted','rejected','needs_review','unmatched')),
  selected_source_feature_ids text[] not null default '{}',
  notes text,
  decided_by uuid references auth.users(id) on delete set null,
  decided_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create index if not exists challenge_inventory_items_edition_idx on public.challenge_inventory_items(edition_id);
create index if not exists challenge_inventory_items_normalized_idx on public.challenge_inventory_items(normalized_name);
create index if not exists reconciliation_candidates_item_idx on public.reconciliation_candidates(inventory_item_id);
create index if not exists reconciliation_decisions_item_idx on public.reconciliation_decisions(inventory_item_id);

alter table public.challenge_editions enable row level security;
alter table public.challenge_inventory_items enable row level security;
alter table public.reconciliation_candidates enable row level security;
alter table public.reconciliation_decisions enable row level security;

create policy "challenge editions are service role readable" on public.challenge_editions for select using (auth.role() = 'service_role');
create policy "challenge inventory items are service role readable" on public.challenge_inventory_items for select using (auth.role() = 'service_role');
create policy "reconciliation candidates are service role readable" on public.reconciliation_candidates for select using (auth.role() = 'service_role');
create policy "reconciliation decisions are service role readable" on public.reconciliation_decisions for select using (auth.role() = 'service_role');

comment on table public.reconciliation_decisions is
  'Trail-level reconciliation review decisions. Accepted reconciliation is still not a verified junction-to-junction TrailSegment.';
